version: '3.1'
services:
 keycloak:
  image: quay.io/keycloak/keycloak:24.0.3
  container_name: keycloak
  command: start-dev
  ports:
  - "8084:8080"
  environment:
  - KEYCLOAK_ADMIN=admin
  - KEYCLOAK_ADMIN_PASSWORD=admin123
  volumes:
  - keycloak_data:/opt/keycloak/data
volumes:
 keycloak_data:
